#!/usr/bin/env python3
"""Unified PhaseRecord data model for workflow phase boundaries.

A single in-memory dataclass renderable to both the session-log markdown
format (for human + git archaeology) and the coordinator handoff_documents
JSON payload (for programmatic consumption by the next phase). Round-trips
losslessly through both representations.

The `write_both()` method runs a three-step best-effort pipeline:
    1. append rendered markdown to openspec/changes/<id>/session-log.md
    2. run sanitize_session_log.py in-place on the file
    3. write the structured payload to the coordinator (or fall back to
       openspec/changes/<id>/handoffs/<phase-slug>-<N>.json on failure)

Each step is independent — failures are logged as warnings but do not raise.

See:
    openspec/changes/phase-record-compaction/contracts/schemas/phase-record.schema.json
    openspec/changes/phase-record-compaction/contracts/schemas/handoff-local-fallback.schema.json
    openspec/changes/phase-record-compaction/design.md (decisions D1, D2, D3, D4, D5, D10)
"""

from __future__ import annotations

import importlib.util
import json
import logging
import re
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Locate the sanitizer next to this file (same directory). Tests can monkey-patch.
_THIS_DIR = Path(__file__).resolve().parent
SANITIZER_SCRIPT = _THIS_DIR / "sanitize_session_log.py"

# Load extract_session_log as a sibling module for header / iteration counting reuse.
# Direct import would require the directory to be a package; this approach keeps
# the script-style layout intact.
_EXTRACT_PATH = _THIS_DIR / "extract_session_log.py"


def _load_extract() -> Any:
    spec = importlib.util.spec_from_file_location("_extract_session_log", _EXTRACT_PATH)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"Could not load {_EXTRACT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ─────────────────────────────────────────────────────────────────────────────
# Data model
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class FileRef:
    """A repo-relative file path with a short description of its relevance."""

    path: str
    description: str = ""


@dataclass
class Decision:
    """A decision recorded at a phase boundary.

    `capability` (kebab-case) is rendered as the inline `architectural: <capability>`
    span and feeds the per-capability decision index regenerated by `make decisions`.
    `supersedes` references a prior decision being reversed (format
    `<change-id>#D<n>` or `<change-id>#<phase-slug>/D<n>`).
    """

    title: str
    rationale: str
    capability: str | None = None
    supersedes: str | None = None


@dataclass
class Alternative:
    """An alternative considered and rejected during the phase."""

    alternative: str
    reason: str


@dataclass
class TradeOff:
    """A trade-off accepted during the phase."""

    accepted: str
    over: str
    reason: str


@dataclass
class PhaseWriteResult:
    """Outcome of `PhaseRecord.write_both()` — best-effort across three steps."""

    markdown_path: Path | None
    sanitized: bool
    handoff_id: str | None
    handoff_local_path: Path | None
    warnings: list[str] = field(default_factory=list)


@dataclass
class PhaseRecord:
    """Unified record of a workflow phase boundary.

    Required fields: change_id, phase_name, agent_type, summary.
    All collection fields default to empty lists; absent sections are
    omitted from the rendered markdown (and from the coordinator payload).
    """

    change_id: str
    phase_name: str
    agent_type: str
    summary: str
    session_id: str | None = None
    decisions: list[Decision] = field(default_factory=list)
    alternatives: list[Alternative] = field(default_factory=list)
    trade_offs: list[TradeOff] = field(default_factory=list)
    open_questions: list[str] = field(default_factory=list)
    completed_work: list[str] = field(default_factory=list)
    in_progress: list[str] = field(default_factory=list)
    next_steps: list[str] = field(default_factory=list)
    relevant_files: list[FileRef] = field(default_factory=list)

    # ─── Rendering ────────────────────────────────────────────────────────

    def render_markdown(self, *, date: str | None = None) -> str:
        """Produce the markdown body for a session-log phase entry.

        The output starts with the `## Phase: ...` header (matching the
        existing template at `skills/session-log/SKILL.md`) and includes
        all populated sections. The `architectural:` and `supersedes:`
        inline spans are preserved exactly so the `make decisions`
        regenerator continues working unchanged.

        Args:
            date: Override date in YYYY-MM-DD format. Defaults to today (UTC).
        """
        date_str = date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
        lines: list[str] = [f"## Phase: {self.phase_name} ({date_str})", ""]
        session_label = self.session_id or "N/A"
        lines.append(f"**Agent**: {self.agent_type} | **Session**: {session_label}")
        lines.append("")

        if self.decisions:
            lines.append("### Decisions")
            for n, decision in enumerate(self.decisions, start=1):
                tags: list[str] = []
                if decision.capability:
                    tags.append(f"`architectural: {decision.capability}`")
                if decision.supersedes:
                    tags.append(f"`supersedes: {decision.supersedes}`")
                tag_part = " " + " ".join(tags) if tags else ""
                lines.append(f"{n}. **{decision.title}**{tag_part} — {decision.rationale}")
            lines.append("")

        if self.alternatives:
            lines.append("### Alternatives Considered")
            for alt in self.alternatives:
                lines.append(f"- {alt.alternative}: rejected because {alt.reason}")
            lines.append("")

        if self.trade_offs:
            lines.append("### Trade-offs")
            for t in self.trade_offs:
                lines.append(f"- Accepted {t.accepted} over {t.over} because {t.reason}")
            lines.append("")

        if self.open_questions:
            lines.append("### Open Questions")
            for q in self.open_questions:
                lines.append(f"- [ ] {q}")
            lines.append("")

        if self.completed_work:
            lines.append("### Completed Work")
            for item in self.completed_work:
                lines.append(f"- {item}")
            lines.append("")

        if self.in_progress:
            lines.append("### In Progress")
            for item in self.in_progress:
                lines.append(f"- {item}")
            lines.append("")

        if self.next_steps:
            lines.append("### Next Steps")
            for item in self.next_steps:
                lines.append(f"- {item}")
            lines.append("")

        if self.relevant_files:
            lines.append("### Relevant Files")
            for fr in self.relevant_files:
                if fr.description:
                    lines.append(f"- `{fr.path}` — {fr.description}")
                else:
                    lines.append(f"- `{fr.path}`")
            lines.append("")

        lines.append("### Context")
        lines.append(self.summary)

        return "\n".join(lines)

    def to_handoff_payload(self) -> dict[str, Any]:
        """Render to the dict shape consumed by `HandoffService.write(...)`.

        Lists of dataclasses are converted to lists of dicts via `asdict`.
        Empty lists are preserved (the schema permits empty arrays); the
        coordinator API treats them as "no entries" without distinction
        from absent fields.
        """
        return {
            "agent_name": self.agent_type,
            "session_id": self.session_id,
            "summary": self.summary,
            "completed_work": list(self.completed_work),
            "in_progress": list(self.in_progress),
            "decisions": [asdict(d) for d in self.decisions],
            "next_steps": list(self.next_steps),
            "relevant_files": [asdict(fr) for fr in self.relevant_files],
        }

    @classmethod
    def from_handoff_payload(
        cls,
        payload: dict[str, Any],
        *,
        change_id: str,
        phase_name: str,
        alternatives: list[Alternative] | None = None,
        trade_offs: list[TradeOff] | None = None,
        open_questions: list[str] | None = None,
    ) -> PhaseRecord:
        """Reconstruct a PhaseRecord from a handoff payload.

        The handoff payload schema is a strict subset of PhaseRecord
        (no alternatives / trade_offs / open_questions). Pass them
        explicitly if you need to restore those fields from a side
        channel; otherwise they default to empty.
        """
        return cls(
            change_id=change_id,
            phase_name=phase_name,
            agent_type=payload.get("agent_name", "unknown"),
            session_id=payload.get("session_id"),
            summary=payload.get("summary", ""),
            decisions=[Decision(**d) for d in payload.get("decisions", [])],
            alternatives=alternatives or [],
            trade_offs=trade_offs or [],
            open_questions=open_questions or [],
            completed_work=list(payload.get("completed_work", [])),
            in_progress=list(payload.get("in_progress", [])),
            next_steps=list(payload.get("next_steps", [])),
            relevant_files=[FileRef(**fr) for fr in payload.get("relevant_files", [])],
        )

    # ─── Persistence pipeline ─────────────────────────────────────────────

    def write_both(
        self,
        *,
        session_log_path: str | Path | None = None,
        handoffs_dir: str | Path | None = None,
        coordinator_writer: Any = None,
        sanitizer_script: str | Path | None = None,
        date: str | None = None,
    ) -> PhaseWriteResult:
        """Best-effort 3-step persistence: markdown → sanitize → coordinator.

        Each step runs independently and logs warnings on failure rather
        than raising. The result captures what succeeded and any warnings.

        Args:
            session_log_path: Override target session-log.md path.
            handoffs_dir: Override directory for local-file fallback.
                Defaults to ``openspec/changes/<change-id>/handoffs/``.
            coordinator_writer: Callable matching
                ``coordination_bridge.try_handoff_write`` signature. Pass
                None to use the default (auto-imports the bridge). Pass a
                test stub to bypass HTTP calls in unit tests.
            sanitizer_script: Override sanitizer script path.
            date: Override date passed to render_markdown.

        Returns:
            PhaseWriteResult capturing markdown_path, sanitized status,
            handoff_id (coordinator) or handoff_local_path (fallback),
            and a list of warnings.
        """
        warnings: list[str] = []

        # Step 1: append markdown
        markdown_path = self._step_append_markdown(session_log_path, date, warnings)

        # Step 2: sanitize in-place
        sanitized = False
        if markdown_path is not None:
            sanitized = self._step_sanitize(markdown_path, sanitizer_script, warnings)
        else:
            warnings.append("step_2_sanitize: skipped (no markdown_path)")

        # Step 3: coordinator write or local fallback
        handoff_id, local_path = self._step_coordinator(
            coordinator_writer, handoffs_dir, warnings
        )

        return PhaseWriteResult(
            markdown_path=markdown_path,
            sanitized=sanitized,
            handoff_id=handoff_id,
            handoff_local_path=local_path,
            warnings=warnings,
        )

    def _step_append_markdown(
        self,
        session_log_path: str | Path | None,
        date: str | None,
        warnings: list[str],
    ) -> Path | None:
        """Append rendered markdown to session-log.md."""
        try:
            extract = _load_extract()
            content = self.render_markdown(date=date)
            # Strip the leading "## Phase: ..." header and date — the helper
            # adds those itself. We pass the body content only.
            body = self._strip_phase_header(content)
            # Use the private markdown-only helper (not the deprecated public
            # append_phase_entry shim) so we don't trigger its DeprecationWarning
            # or its best-effort coordinator write — we do step 3 ourselves.
            return extract._append_phase_entry_markdown(  # type: ignore[no-any-return]  # noqa: SLF001
                self.change_id, self.phase_name, body, session_log_path
            )
        except Exception as exc:  # noqa: BLE001
            warnings.append(f"step_1_markdown: {type(exc).__name__}: {exc}")
            logger.warning("PhaseRecord.write_both step 1 failed: %s", exc)
            return None

    def _step_sanitize(
        self,
        markdown_path: Path,
        sanitizer_script: str | Path | None,
        warnings: list[str],
    ) -> bool:
        """Run sanitize_session_log.py in-place. Returns True on success."""
        script = Path(sanitizer_script) if sanitizer_script else SANITIZER_SCRIPT
        if not script.exists():
            warnings.append(f"step_2_sanitize: sanitizer script not found at {script}")
            return False
        try:
            result = subprocess.run(
                [sys.executable, str(script), str(markdown_path), str(markdown_path)],
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )
            if result.returncode != 0:
                warnings.append(
                    f"step_2_sanitize: exit {result.returncode}: {result.stderr.strip()[:200]}"
                )
                return False
            return True
        except Exception as exc:  # noqa: BLE001
            warnings.append(f"step_2_sanitize: {type(exc).__name__}: {exc}")
            logger.warning("PhaseRecord.write_both step 2 failed: %s", exc)
            return False

    def _step_coordinator(
        self,
        coordinator_writer: Any,
        handoffs_dir: str | Path | None,
        warnings: list[str],
    ) -> tuple[str | None, Path | None]:
        """Write to coordinator; on failure write local-file fallback.

        Returns (handoff_id, handoff_local_path) — exactly one is non-None
        on the success path; both may be None if even the local fallback
        write fails.
        """
        writer = coordinator_writer
        if writer is None:
            writer = self._default_coordinator_writer()

        if writer is not None:
            try:
                payload = self.to_handoff_payload()
                response = writer(
                    agent_id=self.agent_type,
                    summary=self.summary,
                    session_id=self.session_id,
                    content=payload,
                )
                # Bridge returns a dict like {"available": bool, "result": {...}, "error": str}
                # or a direct success dict from the API. Look for handoff_id either way.
                handoff_id = self._extract_handoff_id(response)
                if handoff_id:
                    return handoff_id, None
                # No id and no exception → coordinator returned an error dict
                error_msg = self._extract_coordinator_error(response)
                warnings.append(f"step_3_coordinator: no handoff_id ({error_msg})")
                local_path = self._write_local_fallback(
                    handoffs_dir, error_type="rpc_failed", message=error_msg
                )
                return None, local_path
            except Exception as exc:  # noqa: BLE001
                warnings.append(f"step_3_coordinator: {type(exc).__name__}: {exc}")
                logger.warning("PhaseRecord.write_both step 3 failed: %s", exc)
                local_path = self._write_local_fallback(
                    handoffs_dir, error_type="unreachable", message=str(exc)
                )
                return None, local_path
        else:
            warnings.append("step_3_coordinator: no writer available, using local fallback")
            local_path = self._write_local_fallback(
                handoffs_dir,
                error_type="unknown",
                message="coordination_bridge not importable",
            )
            return None, local_path

    def _default_coordinator_writer(self) -> Any:
        """Locate `coordination_bridge.try_handoff_write` for production use."""
        try:
            # Try import via sys.path first (typical install scenario)
            from coordination_bridge import (
                try_handoff_write,  # type: ignore[import-not-found]
            )

            return try_handoff_write
        except ImportError:
            pass

        # Fall back: locate the bridge by walking up to find skills/coordination-bridge
        cur = _THIS_DIR
        for _ in range(8):
            cur = cur.parent
            candidate = cur / "skills" / "coordination-bridge" / "scripts" / "coordination_bridge.py"
            if candidate.exists():
                spec = importlib.util.spec_from_file_location(
                    "_coordination_bridge", candidate
                )
                if spec is None or spec.loader is None:
                    return None
                module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(module)
                return getattr(module, "try_handoff_write", None)
        return None

    def _extract_handoff_id(self, response: Any) -> str | None:
        if not isinstance(response, dict):
            return None
        # Direct API shape
        direct = response.get("handoff_id")
        if isinstance(direct, str):
            return direct
        # Bridge wrapper shape: {"available": True, "result": {"handoff_id": "..."}}
        result = response.get("result")
        if isinstance(result, dict):
            nested = result.get("handoff_id")
            if isinstance(nested, str):
                return nested
        return None

    def _extract_coordinator_error(self, response: Any) -> str:
        if not isinstance(response, dict):
            return f"non-dict response: {type(response).__name__}"
        for key in ("error", "detail", "message"):
            val = response.get(key)
            if isinstance(val, str) and val:
                return val
        if response.get("available") is False:
            return "coordinator unavailable"
        return "unspecified coordinator error"

    def _write_local_fallback(
        self,
        handoffs_dir: str | Path | None,
        *,
        error_type: str,
        message: str,
        http_status: int | None = None,
    ) -> Path | None:
        """Write the fallback envelope to openspec/changes/<id>/handoffs/<phase>-<N>.json."""
        try:
            base = Path(handoffs_dir) if handoffs_dir else Path(
                f"openspec/changes/{self.change_id}/handoffs"
            )
            base.mkdir(parents=True, exist_ok=True)
            phase_slug = self._phase_slug()
            n = self._next_local_index(base, phase_slug)
            target = base / f"{phase_slug}-{n}.json"
            envelope = {
                "schema_version": 1,
                "written_at": datetime.now(timezone.utc).isoformat(),
                "coordinator_error": {
                    "error_type": error_type,
                    "message": message[:1000],
                    "http_status": http_status,
                },
                "payload": self.to_handoff_payload(),
            }
            target.write_text(json.dumps(envelope, indent=2), encoding="utf-8")
            return target
        except Exception as exc:  # noqa: BLE001
            logger.warning("Local fallback write failed: %s", exc)
            return None

    def _phase_slug(self) -> str:
        return self.phase_name.lower().replace(" ", "-")

    def _next_local_index(self, base: Path, phase_slug: str) -> int:
        existing = sorted(base.glob(f"{phase_slug}-*.json"))
        return len(existing) + 1

    @staticmethod
    def _strip_phase_header(rendered: str) -> str:
        """Remove the leading `## Phase: ...` line and trailing blank.

        `append_phase_entry` produces the phase header itself, so we pass
        only the body content to it. This keeps the existing append helper
        as the single source of truth for header formatting.
        """
        lines = rendered.splitlines()
        if lines and lines[0].startswith("## Phase:"):
            # Drop header + trailing blank line if present
            start = 1
            while start < len(lines) and lines[start] == "":
                start += 1
            return "\n".join(lines[start:])
        return rendered


# ─────────────────────────────────────────────────────────────────────────────
# Markdown parsing — round-trip from render_markdown
# ─────────────────────────────────────────────────────────────────────────────

_PHASE_HEADER_RE = re.compile(r"^## Phase:\s*(.+?)\s*\((\d{4}-\d{2}-\d{2})\)\s*$")
_AGENT_LINE_RE = re.compile(r"^\*\*Agent\*\*:\s*(.+?)\s*\|\s*\*\*Session\*\*:\s*(.+?)\s*$")
_DECISION_LINE_RE = re.compile(
    r"^(\d+)\.\s*\*\*(.+?)\*\*"  # 1. **Title**
    r"((?:\s+`[^`]+`)*)"  # zero or more `key: value` spans
    r"\s+—\s+(.+)$"  # — rationale
)
_TAG_SPAN_RE = re.compile(r"`([^:]+):\s*([^`]+)`")
_ALTERNATIVE_LINE_RE = re.compile(r"^-\s+(.+?):\s*rejected because\s+(.+)$")
_TRADE_OFF_LINE_RE = re.compile(
    r"^-\s+Accepted\s+(.+?)\s+over\s+(.+?)\s+because\s+(.+)$"
)
_FILE_REF_LINE_RE = re.compile(r"^-\s+`([^`]+)`(?:\s+—\s+(.+))?$")


def parse_markdown(text: str, *, change_id: str) -> PhaseRecord:
    """Parse a rendered phase entry back into a PhaseRecord.

    Designed for round-trip with `render_markdown()`: a PhaseRecord
    rendered to markdown and re-parsed produces an equal PhaseRecord
    (modulo date, which is not stored on the record).

    Args:
        text: The full markdown text (must include the `## Phase:` header).
        change_id: The OpenSpec change-id (not derivable from the markdown).

    Raises:
        ValueError: If the phase header line is missing or malformed.
    """
    lines = text.splitlines()
    phase_match = next(
        (m for m in (_PHASE_HEADER_RE.match(line) for line in lines) if m),
        None,
    )
    if phase_match is None:
        raise ValueError("Phase header line `## Phase: <name> (<date>)` not found")
    phase_name = phase_match.group(1)

    sections = _split_sections(lines)

    agent_type = "unknown"
    session_id: str | None = None
    for line in sections.get("__preamble__", []):
        m = _AGENT_LINE_RE.match(line)
        if m:
            agent_type = m.group(1).strip()
            session = m.group(2).strip()
            session_id = None if session == "N/A" else session
            break

    decisions = _parse_decisions(sections.get("Decisions", []))
    alternatives = _parse_alternatives(sections.get("Alternatives Considered", []))
    trade_offs = _parse_trade_offs(sections.get("Trade-offs", []))
    open_questions = _parse_bullet_list(
        sections.get("Open Questions", []), prefix="- [ ] "
    )
    completed_work = _parse_bullet_list(sections.get("Completed Work", []))
    in_progress = _parse_bullet_list(sections.get("In Progress", []))
    next_steps = _parse_bullet_list(sections.get("Next Steps", []))
    relevant_files = _parse_relevant_files(sections.get("Relevant Files", []))
    summary = "\n".join(sections.get("Context", [])).strip()

    return PhaseRecord(
        change_id=change_id,
        phase_name=phase_name,
        agent_type=agent_type,
        session_id=session_id,
        summary=summary,
        decisions=decisions,
        alternatives=alternatives,
        trade_offs=trade_offs,
        open_questions=open_questions,
        completed_work=completed_work,
        in_progress=in_progress,
        next_steps=next_steps,
        relevant_files=relevant_files,
    )


def _split_sections(lines: list[str]) -> dict[str, list[str]]:
    """Split phase entry into sections keyed by `### Heading`.

    Lines before the first `### ` heading land in `__preamble__`.
    """
    sections: dict[str, list[str]] = {"__preamble__": []}
    current = "__preamble__"
    for line in lines:
        if line.startswith("### "):
            current = line[4:].strip()
            sections.setdefault(current, [])
            continue
        if line.startswith("## Phase:"):
            # Skip the phase header itself (already extracted)
            continue
        sections[current].append(line)
    return sections


def _parse_decisions(lines: list[str]) -> list[Decision]:
    out: list[Decision] = []
    for line in lines:
        line = line.rstrip()
        if not line.strip():
            continue
        m = _DECISION_LINE_RE.match(line)
        if not m:
            continue
        title = m.group(2).strip()
        tag_part = m.group(3) or ""
        rationale = m.group(4).strip()
        capability: str | None = None
        supersedes: str | None = None
        for tag_match in _TAG_SPAN_RE.finditer(tag_part):
            key = tag_match.group(1).strip()
            value = tag_match.group(2).strip()
            if key == "architectural":
                capability = value
            elif key == "supersedes":
                supersedes = value
        out.append(
            Decision(
                title=title,
                rationale=rationale,
                capability=capability,
                supersedes=supersedes,
            )
        )
    return out


def _parse_alternatives(lines: list[str]) -> list[Alternative]:
    out: list[Alternative] = []
    for line in lines:
        m = _ALTERNATIVE_LINE_RE.match(line.strip())
        if m:
            out.append(Alternative(alternative=m.group(1).strip(), reason=m.group(2).strip()))
    return out


def _parse_trade_offs(lines: list[str]) -> list[TradeOff]:
    out: list[TradeOff] = []
    for line in lines:
        m = _TRADE_OFF_LINE_RE.match(line.strip())
        if m:
            out.append(
                TradeOff(
                    accepted=m.group(1).strip(),
                    over=m.group(2).strip(),
                    reason=m.group(3).strip(),
                )
            )
    return out


def _parse_bullet_list(lines: list[str], *, prefix: str = "- ") -> list[str]:
    out: list[str] = []
    for line in lines:
        stripped = line.rstrip()
        if stripped.startswith(prefix):
            out.append(stripped[len(prefix):].strip())
    return out


def _parse_relevant_files(lines: list[str]) -> list[FileRef]:
    out: list[FileRef] = []
    for line in lines:
        m = _FILE_REF_LINE_RE.match(line.strip())
        if m:
            out.append(FileRef(path=m.group(1), description=(m.group(2) or "").strip()))
    return out


__all__ = [
    "Alternative",
    "Decision",
    "FileRef",
    "PhaseRecord",
    "PhaseWriteResult",
    "TradeOff",
    "parse_markdown",
]
